DROP TABLE IF EXISTS user_weapons;
DROP TABLE IF EXISTS prefixes;
DROP TABLE IF EXISTS user_characters;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS weapons;
DROP TABLE IF EXISTS shields;
DROP TABLE IF EXISTS grenades;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS class_mods;
DROP TABLE IF EXISTS manufacturers;
DROP TABLE IF EXISTS anointments;

DROP TYPE IF EXISTS wpn_type;
DROP TYPE IF EXISTS char_type;
DROP TYPE IF EXISTS char_class;
DROP TYPE IF EXISTS rarity_type;
DROP TYPE IF EXISTS elmnt;
